agendas:
  quentin:
    calendar_id: "ja53enipie6bc0b7sdldvlf528@group.calendar.google.com"
    default: true
    default_color: "11"
    git_repo_path: "/home/quentin/gdrive/cours/git_cours/cours/"
    longname: "quentin"
    shortname: "q"

  sadia:
    calendar_id: "52c9b797bc750981c0630a8fbe84dc94a8751458c00340994d81c99cd55bcd92@group.calendar.google.com"
    default: false
    default_color: "3"
    git_repo_path: "/home/quentin/git_repos/sadia/2023_PS/"
    longname: "sadia"
    shortname: "s"
