agendas:
  quentin:
    calendar_id: "ja53enipie6bc0b7sdldvlf528@group.calendar.google.com"
    default: true
    default_color: "11"
    git_repo_path: "/home/quentin/gdrive/cours/git_cours/cours/"
    longname: "quentin"
    shortname: "q"

  sadia:
    calendar_id: "12a4d2b4f73f69f3bff737fe718a2a8d700c42523932da3f3a6fd5f730373d18@group.calendar.google.com"
    default: false
    default_color: "3"
    git_repo_path: "/home/quentin/git_repos/sadia/2023_PS/"
    longname: "sadia"
    shortname: "s"
