agendas:
  quentin:
    shortname: "q"
    longname: "quentin"
    calendar_id: "ja53enipie6bc0b7sdldvlf528@group.calendar.google.com"
    git_repo_path: "/home/quentin/gdrive/cours/git_cours/cours/"
    default_color: "11"
    default: true

  sadia:
    shortname: "s"
    longname: "sadia"
    calendar_id: "aze"
    git_repo_path: "aze"
    default_color: "3"
    default: false
